---
# tasks file for node-exporter

- name: get node-exporter tar
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: copy bin to bin
  copy:
    src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: true
    mode: +x

- name: add node_exporter group
  group:
    name: node_exporter
    state: present

- name: add node_exporter user
  user:
    name: node_exporter
    group: node_exporter
    create_home: no
    shell: /sbin/nologin
    system: true

- name: copy node_exporter systemd unit
  copy:
    src: ../files/node_exporter.service
    dest: /lib/systemd/system/node_exporter.service

- name: add ports to firewall
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 9100/tcp

- name: enable and start node_exporter
  systemd:
    name: node_exporter
    state: started
    daemon_reload: true
    enabled: true
    